-- MySQL Script generated by MySQL Workbench
-- Mon Nov 14 12:28:16 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Artist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Artist` (
  `Artist_id` INT NOT NULL,
  `Artist_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Artist_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Album`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Album` (
  `Album_id` INT NOT NULL,
  `Album_name` VARCHAR(45) NOT NULL,
  `Artist_id` VARCHAR(45) NULL,
  `Artist_Artist_id` INT NOT NULL,
  PRIMARY KEY (`Album_id`, `Artist_Artist_id`),
  INDEX `fk_Album_Artist1_idx` (`Artist_Artist_id` ASC),
  CONSTRAINT `fk_Album_Artist1`
    FOREIGN KEY (`Artist_Artist_id`)
    REFERENCES `mydb`.`Artist` (`Artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Track`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Track` (
  `Track_id` INT NOT NULL,
  `Track_name` VARCHAR(45) NOT NULL,
  `time` DATETIME NOT NULL,
  `Album_Album_id` INT NOT NULL,
  `Artist_Artist_id` INT NOT NULL,
  PRIMARY KEY (`Track_id`, `Album_Album_id`, `Artist_Artist_id`),
  INDEX `fk_Track_Album1_idx` (`Album_Album_id` ASC),
  INDEX `fk_Track_Artist1_idx` (`Artist_Artist_id` ASC),
  CONSTRAINT `fk_Track_Album1`
    FOREIGN KEY (`Album_Album_id`)
    REFERENCES `mydb`.`Album` (`Album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Track_Artist1`
    FOREIGN KEY (`Artist_Artist_id`)
    REFERENCES `mydb`.`Artist` (`Artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Played`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Played` (
  `Played` INT NOT NULL,
  `Track_Track_id` INT NOT NULL,
  `Track_Album_Album_id` INT NOT NULL,
  `Artist_Artist_id` INT NOT NULL,
  `Album_Album_id` INT NOT NULL,
  `Album_Artist_Artist_id` INT NOT NULL,
  PRIMARY KEY (`Played`, `Track_Track_id`, `Track_Album_Album_id`, `Artist_Artist_id`, `Album_Album_id`, `Album_Artist_Artist_id`),
  INDEX `fk_Played_Track1_idx` (`Track_Track_id` ASC, `Track_Album_Album_id` ASC),
  INDEX `fk_Played_Artist1_idx` (`Artist_Artist_id` ASC),
  INDEX `fk_Played_Album1_idx` (`Album_Album_id` ASC, `Album_Artist_Artist_id` ASC),
  CONSTRAINT `fk_Played_Track1`
    FOREIGN KEY (`Track_Track_id` , `Track_Album_Album_id`)
    REFERENCES `mydb`.`Track` (`Track_id` , `Album_Album_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Played_Artist1`
    FOREIGN KEY (`Artist_Artist_id`)
    REFERENCES `mydb`.`Artist` (`Artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Played_Album1`
    FOREIGN KEY (`Album_Album_id` , `Album_Artist_Artist_id`)
    REFERENCES `mydb`.`Album` (`Album_id` , `Artist_Artist_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
